-- Seeder da Biblioteca de Exercícios nativa do VocalFlow.
-- Idempotente: pode ser executado mais de uma vez sem duplicar dados,
-- graças ao ON CONFLICT (title) DO NOTHING.

insert into exercises (title, category, objective, description, duration_minutes, level, tags, order_index) values

-- Respiração
($$Respiração Diafragmática Básica$$, 'Respiração', $$Ensinar o aluno a direcionar o ar para o diafragma em vez do peito, base de toda técnica vocal saudável.$$, $$Sente-se ou fique em pé com a coluna alongada. Coloque uma mão no abdômen e outra no peito. Inspire pelo nariz contando até 4, sentindo o abdômen expandir enquanto o peito permanece quase imóvel. Expire lentamente pela boca contando até 6, sentindo o abdômen retornar à posição inicial. Repita mantendo o ritmo constante e sem tensionar os ombros.$$, 5, 'Iniciante', array['respiração','diafragma','iniciante','relaxamento'], 1),

($$Respiração em 4 Tempos (Box Breathing)$$, 'Respiração', $$Desenvolver controle e consciência do ciclo respiratório através de contagens iguais.$$, $$Inspire contando 4 tempos, sustenha o ar por 4 tempos, expire em 4 tempos e sustenha os pulmões vazios por mais 4 tempos antes de reiniciar o ciclo. Mantenha os ombros relaxados durante toda a sequência. Esse exercício também ajuda a reduzir a ansiedade antes de apresentações.$$, 5, 'Iniciante', array['respiração','controle','box-breathing','iniciante'], 2),

($$Respiração Costal-Diafragmática com Resistência$$, 'Respiração', $$Fortalecer a musculatura respiratória e prolongar a capacidade de sustentação do ar durante o canto.$$, $$Inspire profundamente ativando a respiração costal-diafragmática. Ao expirar, emita um som de "sss" contínuo e uniforme, tentando sustentar por pelo menos 20 segundos sem que o som varie em intensidade. Aumente gradualmente o tempo de sustentação ao longo da prática, sempre priorizando a qualidade e constância do fluxo de ar sobre a duração.$$, 10, 'Intermediário', array['respiração','resistência','apoio','intermediário'], 3),

-- Aquecimento Vocal
($$Vibração de Lábios (Lip Trill) em Glissando$$, 'Aquecimento Vocal', $$Aquecer as pregas vocais com baixa pressão subglótica, liberando tensão nos lábios e na mandíbula.$$, $$Vibre os lábios como um motor de carro (lip trill) enquanto deixa a voz deslizar suavemente do grave ao agudo e de volta ao grave, em glissandos contínuos. Mantenha o fluxo de ar constante e evite pressionar os lábios com força excessiva. Explore toda a extensão confortável da voz.$$, 5, 'Iniciante', array['aquecimento','lip-trill','glissando','iniciante'], 4),

($$Escala de 5 Notas em Staccato$$, 'Aquecimento Vocal', $$Ativar a musculatura vocal de forma leve e progressiva no início do aquecimento.$$, $$Cante uma escala de 5 notas ascendente e descendente (dó-ré-mi-fá-sol-fá-mi-ré-dó) utilizando a sílaba "Ha" em staccato, com notas curtas e bem articuladas. Suba um semitom a cada repetição, avançando conforme o conforto vocal permitir, sem forçar a região aguda.$$, 10, 'Iniciante', array['aquecimento','escala','staccato','iniciante'], 5),

($$Sirene Vocal Completa$$, 'Aquecimento Vocal', $$Conectar todos os registros vocais em um único movimento contínuo, preparando a voz para exercícios mais técnicos.$$, $$Partindo da nota mais grave confortável, deslize a voz suavemente até a nota mais aguda possível e retorne, como uma sirene, usando a vogal "U" ou a consoante "V". Mantenha o som contínuo, sem quebras perceptíveis entre os registros. Execute de 8 a 10 repetições, respirando profundamente entre elas.$$, 10, 'Intermediário', array['aquecimento','sirene','registros','intermediário'], 6),

-- Apoio Respiratório
($$Sustentação de Nota com Contagem$$, 'Apoio Respiratório', $$Treinar a sustentação de uma nota única com apoio constante do diafragma.$$, $$Escolha uma nota confortável na região média da voz e sustente-a na vogal "A" por 10 segundos, contando mentalmente. Mantenha a intensidade e a afinação estáveis do início ao fim, sem deixar o volume cair. Aumente a duração gradualmente conforme a resistência respiratória melhorar.$$, 5, 'Iniciante', array['apoio','sustentação','respiração','iniciante'], 7),

($$Messa di Voce (Crescendo-Decrescendo)$$, 'Apoio Respiratório', $$Desenvolver controle fino da pressão de ar para variar dinâmica sem perder a afinação ou o apoio.$$, $$Sustente uma nota confortável começando em volume muito baixo (piano), cresça gradualmente até o volume máximo controlado (forte) e depois decresça de volta ao piano, tudo em uma única respiração. Mantenha a afinação constante durante toda a variação dinâmica. Exercício clássico do repertório clássico e pop para controle de apoio.$$, 10, 'Intermediário', array['apoio','dinâmica','messa-di-voce','intermediário'], 8),

($$Staccato Rápido com Apoio Abdominal$$, 'Apoio Respiratório', $$Refinar a resposta rápida do apoio abdominal em passagens rítmicas ágeis.$$, $$Cante uma sequência de notas curtas e repetidas em staccato rápido (por exemplo, 8 repetições da mesma nota em ritmo de colcheia) sentindo um pequeno impulso do abdômen em cada nota, como pequenos "socos" de ar controlados. Aumente a velocidade progressivamente, mantendo a precisão rítmica e evitando tensão na garganta.$$, 10, 'Avançado', array['apoio','staccato','agilidade','avançado'], 9),

-- Afinação
($$Intervalos de Terça Ascendentes e Descendentes$$, 'Afinação', $$Desenvolver a percepção auditiva e a precisão para cantar intervalos pequenos com afinação exata.$$, $$Com apoio de um instrumento ou app de afinação, cante intervalos de terça (dó-mi, ré-fá, mi-sol...) subindo e descendo por toda a extensão confortável da voz. Ouça atentamente a nota de referência antes de cantar e confirme a afinação com o instrumento após cada intervalo.$$, 10, 'Iniciante', array['afinação','intervalos','ouvido','iniciante'], 10),

($$Escala Maior Completa com Referência de Piano$$, 'Afinação', $$Consolidar a afinação em escalas maiores completas, identificando e corrigindo desvios de forma imediata.$$, $$Cante a escala maior completa (dó-ré-mi-fá-sol-lá-si-dó) ascendente e descendente acompanhado de um piano ou teclado, nota por nota. Pare imediatamente caso perceba um desvio de afinação, identifique a nota problemática e repita o trecho até corrigir. Suba de tonalidade gradualmente.$$, 10, 'Intermediário', array['afinação','escala','piano','intermediário'], 11),

($$Arpejos com Salto de Oitava$$, 'Afinação', $$Aprimorar a precisão de afinação em saltos melódicos amplos, comuns em repertório avançado.$$, $$Cante arpejos maiores que incluem um salto de oitava (dó-mi-sol-dó agudo) e o caminho inverso, garantindo que a nota do salto seja atingida com precisão imediata, sem "escorregar" até a afinação correta. Use um teclado para verificar cada salto antes de avançar para a próxima tonalidade.$$, 15, 'Avançado', array['afinação','arpejo','saltos','avançado'], 12),

-- Voz de Peito
($$Notas Faladas na Região de Peito$$, 'Voz de Peito', $$Conectar a fala natural ao canto na região grave e média, identificando a sensação da voz de peito.$$, $$Fale frases curtas em tom de conversa normal e observe a vibração sentida no peito e na caixa torácica. Em seguida, cante as mesmas frases na mesma região de altura, mantendo essa sensação de vibração torácica e a naturalidade da fala.$$, 5, 'Iniciante', array['voz-de-peito','registro','iniciante','fala'], 13),

($$Escala Descendente em Voz de Peito com "Ga"$$, 'Voz de Peito', $$Fortalecer a voz de peito na região média-grave, mantendo clareza e potência sem tensão excessiva.$$, $$Partindo de uma nota confortável na região média, cante uma escala descendente de 5 notas usando a sílaba "Ga", mantendo o som cheio e a sensação de vibração no peito até a nota mais grave da sequência. Evite empurrar o som com a garganta; a potência deve vir do apoio respiratório.$$, 10, 'Intermediário', array['voz-de-peito','escala','potência','intermediário'], 14),

($$Extensão da Voz de Peito com Vogais Abertas$$, 'Voz de Peito', $$Ampliar com segurança o limite superior confortável da voz de peito, adiando a passagem para a voz de cabeça.$$, $$Usando as vogais "A" e "É" (abertas), cante escalas ascendentes tentando manter a qualidade de peito o máximo possível antes da região de passagem, sem forçar ou gritar. Pare o exercício ao primeiro sinal de tensão na garganta e retome no dia seguinte com um semitom de acréscimo. Exige acompanhamento e feedback constante do professor.$$, 15, 'Avançado', array['voz-de-peito','extensão','avançado','passagem'], 15),

-- Voz de Cabeça
($$Deslizamento Suave para o Registro de Cabeça$$, 'Voz de Cabeça', $$Familiarizar o aluno com a sensação leve e "flutuante" da voz de cabeça.$$, $$Partindo de uma nota aguda confortável, deslize suavemente para cima usando a vogal "U", permitindo que a voz "afine" naturalmente para um som mais leve e ressonante na cabeça. Evite qualquer esforço na garganta — a sensação deve ser de leveza, quase como um assobio vocal.$$, 5, 'Iniciante', array['voz-de-cabeça','leveza','iniciante','falsete'], 16),

($$Escalas em Falsete Controlado$$, 'Voz de Cabeça', $$Desenvolver controle e estabilidade no registro de cabeça através de escalas melódicas.$$, $$Cante escalas de 5 notas inteiramente na voz de cabeça/falsete, com a vogal "U" ou "O", mantendo volume e timbre constantes em todas as notas. Preste atenção especial para que a transição entre as notas seja suave, sem quebras de ar ou variações abruptas de intensidade.$$, 10, 'Intermediário', array['voz-de-cabeça','falsete','controle','intermediário'], 17),

($$Passagem Peito-Cabeça em Vogal "U"$$, 'Voz de Cabeça', $$Suavizar a transição entre voz de peito e voz de cabeça, reduzindo a quebra perceptível na região de passagem.$$, $$Cante um glissando lento subindo da voz de peito até a voz de cabeça na vogal "U", tentando minimizar qualquer quebra ou mudança abrupta de timbre na transição. Grave-se e ouça atentamente onde a quebra ocorre, repetindo o trecho específico da passagem isoladamente até suavizá-lo.$$, 10, 'Avançado', array['voz-de-cabeça','passagem','avançado','transição'], 18),

-- Voz Mista
($$Notas de Passagem com "Nay"$$, 'Voz Mista', $$Explorar a zona de mixagem entre peito e cabeça usando uma sílaba que favorece o equilíbrio entre os registros.$$, $$Cante a sílaba "Nay" (como em "neigh", o som de um cavalo) em notas próximas à região de passagem da voz, sentindo o som se apoiar tanto na ressonância nasal quanto na potência do peito. Essa sílaba é amplamente usada por professores de canto justamente por facilitar o acesso à voz mista.$$, 10, 'Intermediário', array['voz-mista','passagem','nay','intermediário'], 19),

($$Sirene com Foco na Zona de Mixagem$$, 'Voz Mista', $$Manter a mixagem de registros estável ao atravessar repetidamente a região de passagem.$$, $$Execute o exercício de sirene (deslizamento contínuo do grave ao agudo) concentrando a atenção especificamente na região de passagem, tentando manter o mesmo timbre "misto" ao atravessá-la repetidamente, em vez de alternar abruptamente entre peito puro e cabeça pura.$$, 10, 'Intermediário', array['voz-mista','sirene','passagem','intermediário'], 20),

($$Escala Completa em Voz Mista$$, 'Voz Mista', $$Cantar uma escala completa de uma oitava mantendo a mixagem de registros do início ao fim, sem quebras perceptíveis.$$, $$Cante uma escala maior completa (uma oitava) do grave ao agudo e de volta, mantendo consistentemente a sensação de voz mista — nem puramente de peito, nem puramente de cabeça — em toda a extensão. Use a vogal "É" fechada ou "I" para facilitar o equilíbrio. Interrompa ao primeiro sinal de fadiga vocal.$$, 15, 'Avançado', array['voz-mista','escala','avançado','equilíbrio'], 21),

-- Extensão Vocal
($$Escala Cromática Ascendente$$, 'Extensão Vocal', $$Ampliar a extensão vocal de forma gradual e segura, trabalhando semitom a semitom.$$, $$Cante uma escala cromática (subindo semitom a semitom) partindo de uma nota confortável, usando a vogal "A". Avance apenas até onde a voz permanecer confortável e sem esforço perceptível, marcando mentalmente o ponto de parada de cada sessão para acompanhar a evolução da extensão ao longo das semanas.$$, 10, 'Intermediário', array['extensão','cromática','gradual','intermediário'], 22),

($$Alongamento de Extensão com Glissando Amplo$$, 'Extensão Vocal', $$Alongar suavemente os limites da extensão vocal sem forçar a voz.$$, $$Execute glissandos amplos, do grave mais confortável ao agudo mais confortável e vice-versa, na vogal "U", tentando ganhar um pouco mais de amplitude a cada repetição — mas sempre respeitando o limite de conforto do dia. A extensão vocal se expande com consistência ao longo do tempo, não com força em uma única sessão.$$, 10, 'Intermediário', array['extensão','glissando','alongamento','intermediário'], 23),

($$Exploração de Notas-Limite (Agudos e Graves)$$, 'Extensão Vocal', $$Mapear e expandir com segurança os extremos atuais da extensão vocal do aluno.$$, $$Com supervisão do professor, explore cuidadosamente as notas mais agudas e mais graves que a voz consegue produzir com qualidade (sem forçar ou "quebrar"), documentando os limites atuais. Repita periodicamente para acompanhar a evolução. Interrompa imediatamente ao sentir qualquer desconforto na garganta.$$, 15, 'Avançado', array['extensão','limites','avançado','mapeamento'], 24),

-- Ressonância
($$Zumbido Nasal (Humming)$$, 'Ressonância', $$Localizar e ativar a ressonância nasal e facial de forma simples e acessível.$$, $$Produza um zumbido (humming) com a boca fechada, sentindo a vibração nos lábios, no nariz e na região dos ossos da face. Explore diferentes alturas, sempre buscando maximizar essa sensação de vibração facial, que indica boa ressonância.$$, 5, 'Iniciante', array['ressonância','humming','iniciante','face'], 25),

($$Ressonância em "Ng" com Vibração Facial$$, 'Ressonância', $$Aprofundar a sensação de ressonância nasal usando o som "Ng" (como em "sing") em frases melódicas.$$, $$Cante pequenas melodias usando apenas o som "Ng", mantendo a vibração concentrada na região nasal e nos ossos da face durante toda a frase melódica. Depois, transfira essa mesma sensação de vibração para uma vogal aberta, como "A", cantando a mesma melodia.$$, 10, 'Intermediário', array['ressonância','ng','vibração','intermediário'], 26),

($$Projeção de Voz com Foco no Masque$$, 'Ressonância', $$Aumentar a projeção vocal utilizando a ressonância da "máscara" facial, sem depender de força na garganta.$$, $$Cante frases inteiras direcionando mentalmente o som para a região da "máscara" (nariz, bochechas e testa), buscando uma sensação de projeção natural sem aumentar o esforço na garganta. Compare o volume percebido antes e depois de ajustar o foco de ressonância — a diferença deve ser perceptível sem esforço extra.$$, 10, 'Avançado', array['ressonância','projeção','masque','avançado'], 27),

-- Dicção
($$Trava-línguas Vocalizados$$, 'Dicção', $$Melhorar a agilidade articulatória da língua e dos lábios através de trava-línguas cantados.$$, $$Escolha um trava-língua simples e curto e cante-o em uma nota ou escala curta, articulando cada consoante com clareza exagerada. Aumente a velocidade gradualmente, sem sacrificar a clareza da pronúncia.$$, 5, 'Iniciante', array['dicção','trava-língua','articulação','iniciante'], 28),

($$Consoantes Explosivas em Staccato$$, 'Dicção', $$Fortalecer a precisão e a energia na articulação de consoantes explosivas (P, T, K, B, D, G).$$, $$Cante sequências curtas repetindo consoantes explosivas isoladas (por exemplo "Pa-Pa-Pa-Pa", "Ta-Ta-Ta-Ta", "Ka-Ka-Ka-Ka") em staccato rápido, em uma única nota. Sinta o impulso de ar de cada consoante vindo do apoio abdominal, não apenas da boca.$$, 10, 'Intermediário', array['dicção','consoantes','staccato','intermediário'], 29),

($$Texto Cantado com Articulação Exagerada$$, 'Dicção', $$Aplicar a dicção trabalhada em um contexto musical real, mantendo clareza mesmo em passagens rápidas ou agudas.$$, $$Escolha um trecho de uma música do repertório do aluno e cante-o duas vezes: primeiro exagerando propositalmente cada consoante e vogal, depois normalmente — mas buscando manter parte dessa clareza conquistada. Grave as duas versões e compare a inteligibilidade do texto entre elas.$$, 15, 'Avançado', array['dicção','repertório','articulação','avançado'], 30)

on conflict (title) do nothing;
