-- Seeder de la Biblioteca de Ejercicios nativa de VocalFlow.
-- Idempotente: puede ejecutarse más de una vez sin duplicar datos.
--
-- Desde la migration 0018, cada profesor tiene su PROPIA copia de la
-- biblioteca. Este seed solo inserta el "molde" (teacher_id nulo), que se
-- copia automáticamente a cada profesor la primera vez que inicia sesión
-- (ver ensureExerciseLibrary en services/exercises.ts). No inserta nada
-- directamente en la cuenta de ningún profesor.

insert into exercises (title, category, objective, description, duration_minutes, level, tags, order_index) values

-- Respiración
($$Respiración Diafragmática Básica$$, 'Respiración', $$Enseñar al alumno a dirigir el aire hacia el diafragma en vez del pecho, base de toda técnica vocal saludable.$$, $$Siéntate o ponte de pie con la columna alargada. Coloca una mano en el abdomen y otra en el pecho. Inspira por la nariz contando hasta 4, sintiendo el abdomen expandirse mientras el pecho permanece casi inmóvil. Exhala lentamente por la boca contando hasta 6, sintiendo el abdomen volver a la posición inicial. Repite manteniendo el ritmo constante y sin tensar los hombros.$$, 5, 'Principiante', array['respiración','diafragma','principiante','relajación'], 1),

($$Respiración en 4 Tiempos (Box Breathing)$$, 'Respiración', $$Desarrollar control y conciencia del ciclo respiratorio a través de conteos iguales.$$, $$Inspira contando 4 tiempos, sostén el aire por 4 tiempos, exhala en 4 tiempos y sostén los pulmones vacíos por 4 tiempos más antes de reiniciar el ciclo. Mantén los hombros relajados durante toda la secuencia. Este ejercicio también ayuda a reducir la ansiedad antes de presentaciones.$$, 5, 'Principiante', array['respiración','control','box-breathing','principiante'], 2),

($$Respiración Costal-Diafragmática con Resistencia$$, 'Respiración', $$Fortalecer la musculatura respiratoria y prolongar la capacidad de sostener el aire durante el canto.$$, $$Inspira profundamente activando la respiración costal-diafragmática. Al exhalar, emite un sonido de "sss" continuo y uniforme, intentando sostenerlo por al menos 20 segundos sin que el sonido varíe en intensidad. Aumenta gradualmente el tiempo de sostenimiento a lo largo de la práctica, priorizando siempre la calidad y constancia del flujo de aire sobre la duración.$$, 10, 'Intermedio', array['respiración','resistencia','apoyo','intermedio'], 3),

-- Calentamiento Vocal
($$Vibración de Labios (Lip Trill) en Glissando$$, 'Calentamiento Vocal', $$Calentar las cuerdas vocales con baja presión subglótica, liberando tensión en labios y mandíbula.$$, $$Vibra los labios como un motor de auto (lip trill) mientras dejas que la voz se deslice suavemente del grave al agudo y de vuelta al grave, en glissandos continuos. Mantén el flujo de aire constante y evita presionar los labios con fuerza excesiva. Repite explorando toda la extensión cómoda de la voz.$$, 5, 'Principiante', array['calentamiento','lip-trill','glissando','principiante'], 4),

($$Escala de 5 Notas en Staccato$$, 'Calentamiento Vocal', $$Activar la musculatura vocal de forma leve y progresiva al inicio del calentamiento.$$, $$Canta una escala de 5 notas ascendente y descendente (do-re-mi-fa-sol-fa-mi-re-do) usando la sílaba "Ha" en staccato, con notas cortas y bien articuladas. Sube un semitono en cada repetición, avanzando según lo permita la comodidad vocal, sin forzar la región aguda.$$, 10, 'Principiante', array['calentamiento','escala','staccato','principiante'], 5),

($$Sirena Vocal Completa$$, 'Calentamiento Vocal', $$Conectar todos los registros vocales en un único movimiento continuo, preparando la voz para ejercicios más técnicos.$$, $$Partiendo de la nota más grave cómoda, desliza la voz suavemente hasta la nota más aguda posible y regresa, como una sirena, usando la vocal "U" o la consonante "V". Mantén el sonido continuo, sin quiebres perceptibles entre los registros. Ejecuta de 8 a 10 repeticiones, respirando profundamente entre ellas.$$, 10, 'Intermedio', array['calentamiento','sirena','registros','intermedio'], 6),

-- Apoyo Respiratorio
($$Sostenimiento de Nota con Conteo$$, 'Apoyo Respiratorio', $$Entrenar el sostenimiento de una nota única con apoyo constante del diafragma.$$, $$Elige una nota cómoda en la región media de la voz y sostenla en la vocal "A" por 10 segundos, contando mentalmente. Mantén la intensidad y la afinación estables de principio a fin, sin dejar que el volumen caiga. Aumenta la duración gradualmente conforme mejore la resistencia respiratoria.$$, 5, 'Principiante', array['apoyo','sostenimiento','respiración','principiante'], 7),

($$Messa di Voce (Crescendo-Decrescendo)$$, 'Apoyo Respiratorio', $$Desarrollar control fino de la presión de aire para variar la dinámica sin perder la afinación o el apoyo.$$, $$Sostén una nota cómoda comenzando en volumen muy bajo (piano), crece gradualmente hasta el volumen máximo controlado (forte) y luego decrece de vuelta al piano, todo en una sola respiración. Mantén la afinación constante durante toda la variación dinámica. Este es un ejercicio clásico del repertorio clásico y pop para control de apoyo.$$, 10, 'Intermedio', array['apoyo','dinámica','messa-di-voce','intermedio'], 8),

($$Staccato Rápido con Apoyo Abdominal$$, 'Apoyo Respiratorio', $$Refinar la respuesta rápida del apoyo abdominal en pasajes rítmicos ágiles.$$, $$Canta una secuencia de notas cortas y repetidas en staccato rápido (por ejemplo, 8 repeticiones de la misma nota en ritmo de corchea) sintiendo un pequeño impulso del abdomen en cada nota, como pequeños "golpes" de aire controlados. Aumenta la velocidad progresivamente, manteniendo la precisión rítmica y evitando tensión en la garganta.$$, 10, 'Avanzado', array['apoyo','staccato','agilidad','avanzado'], 9),

-- Afinación
($$Intervalos de Tercera Ascendentes y Descendentes$$, 'Afinación', $$Desarrollar la percepción auditiva y la precisión para cantar intervalos pequeños con afinación exacta.$$, $$Con apoyo de un instrumento o app de afinación, canta intervalos de tercera (do-mi, re-fa, mi-sol...) subiendo y bajando por toda la extensión cómoda de la voz. Escucha atentamente la nota de referencia antes de cantar y confirma la afinación con el instrumento después de cada intervalo.$$, 10, 'Principiante', array['afinación','intervalos','oído','principiante'], 10),

($$Escala Mayor Completa con Referencia de Piano$$, 'Afinación', $$Consolidar la afinación en escalas mayores completas, identificando y corrigiendo desvíos de forma inmediata.$$, $$Canta la escala mayor completa (do-re-mi-fa-sol-la-si-do) ascendente y descendente acompañado de un piano o teclado, nota por nota. Detente de inmediato si percibes un desvío de afinación, identifica la nota problemática y repite el fragmento hasta corregirlo. Sube de tonalidad gradualmente.$$, 10, 'Intermedio', array['afinación','escala','piano','intermedio'], 11),

($$Arpegios con Salto de Octava$$, 'Afinación', $$Mejorar la precisión de afinación en saltos melódicos amplios, comunes en repertorio avanzado.$$, $$Canta arpegios mayores que incluyan un salto de octava (do-mi-sol-do agudo) y el camino inverso, garantizando que la nota del salto sea alcanzada con precisión inmediata, sin "resbalar" hasta la afinación correcta. Usa un teclado para verificar cada salto antes de avanzar a la siguiente tonalidad.$$, 15, 'Avanzado', array['afinación','arpegio','saltos','avanzado'], 12),

-- Voz de Pecho
($$Notas Habladas en la Región de Pecho$$, 'Voz de Pecho', $$Conectar el habla natural al canto en la región grave y media, identificando la sensación de la voz de pecho.$$, $$Habla frases cortas en tono de conversación normal y observa la vibración sentida en el pecho y la caja torácica. Luego, canta las mismas frases en la misma región de altura, manteniendo esa sensación de vibración torácica y la naturalidad del habla.$$, 5, 'Principiante', array['voz-de-pecho','registro','principiante','habla'], 13),

($$Escala Descendente en Voz de Pecho con "Ga"$$, 'Voz de Pecho', $$Fortalecer la voz de pecho en la región media-grave, manteniendo claridad y potencia sin tensión excesiva.$$, $$Partiendo de una nota cómoda en la región media, canta una escala descendente de 5 notas usando la sílaba "Ga", manteniendo el sonido pleno y la sensación de vibración en el pecho hasta la nota más grave de la secuencia. Evita empujar el sonido con la garganta; la potencia debe venir del apoyo respiratorio.$$, 10, 'Intermedio', array['voz-de-pecho','escala','potencia','intermedio'], 14),

($$Extensión de la Voz de Pecho con Vocales Abiertas$$, 'Voz de Pecho', $$Ampliar con seguridad el límite superior cómodo de la voz de pecho, posponiendo el paso a la voz de cabeza.$$, $$Usando las vocales "A" y "E" (abiertas), canta escalas ascendentes intentando mantener la calidad de pecho el máximo posible antes de la región de pasaje, sin forzar ni gritar. Detén el ejercicio ante la primera señal de tensión en la garganta y retómalo al día siguiente con un semitono más. Este ejercicio requiere acompañamiento y retroalimentación constante del profesor.$$, 15, 'Avanzado', array['voz-de-pecho','extensión','avanzado','pasaje'], 15),

-- Voz de Cabeza
($$Deslizamiento Suave hacia el Registro de Cabeza$$, 'Voz de Cabeza', $$Familiarizar al alumno con la sensación ligera y "flotante" de la voz de cabeza.$$, $$Partiendo de una nota aguda cómoda, desliza suavemente hacia arriba usando la vocal "U", permitiendo que la voz "afine" naturalmente hacia un sonido más ligero y resonante en la cabeza. Evita cualquier esfuerzo en la garganta — la sensación debe ser de ligereza, casi como un silbido vocal.$$, 5, 'Principiante', array['voz-de-cabeza','ligereza','principiante','falsete'], 16),

($$Escalas en Falsete Controlado$$, 'Voz de Cabeza', $$Desarrollar control y estabilidad en el registro de cabeza a través de escalas melódicas.$$, $$Canta escalas de 5 notas enteramente en la voz de cabeza/falsete, con la vocal "U" o "O", manteniendo volumen y timbre constantes en todas las notas. Presta atención especial para que la transición entre las notas sea suave, sin quiebres de aire ni variaciones abruptas de intensidad.$$, 10, 'Intermedio', array['voz-de-cabeza','falsete','control','intermedio'], 17),

($$Pasaje Pecho-Cabeza en Vocal "U"$$, 'Voz de Cabeza', $$Suavizar la transición entre voz de pecho y voz de cabeza, reduciendo el quiebre perceptible en la región de pasaje.$$, $$Canta un glissando lento subiendo de la voz de pecho hasta la voz de cabeza en la vocal "U", intentando minimizar cualquier quiebre o cambio abrupto de timbre en la transición. Grábate y escucha atentamente dónde ocurre el quiebre, repitiendo el fragmento específico del pasaje de forma aislada hasta suavizarlo.$$, 10, 'Avanzado', array['voz-de-cabeza','pasaje','avanzado','transición'], 18),

-- Voz Mixta
($$Notas de Pasaje con "Nay"$$, 'Voz Mixta', $$Explorar la zona de mezcla entre pecho y cabeza usando una sílaba que favorece el equilibrio entre los registros.$$, $$Canta la sílaba "Nay" (como en inglés "neigh", el sonido de un caballo) en notas cercanas a la región de pasaje de la voz, sintiendo que el sonido se apoya tanto en la resonancia nasal como en la potencia del pecho. Esta sílaba es ampliamente usada por profesores de canto justamente por facilitar el acceso a la voz mixta.$$, 10, 'Intermedio', array['voz-mixta','pasaje','nay','intermedio'], 19),

($$Sirena con Foco en la Zona de Mezcla$$, 'Voz Mixta', $$Mantener la mezcla de registros estable al atravesar repetidamente la región de pasaje.$$, $$Ejecuta el ejercicio de sirena (deslizamiento continuo del grave al agudo) concentrando la atención específicamente en la región de pasaje, intentando mantener el mismo timbre "mixto" al atravesarla repetidamente, en vez de alternar bruscamente entre pecho puro y cabeza pura.$$, 10, 'Intermedio', array['voz-mixta','sirena','pasaje','intermedio'], 20),

($$Escala Completa en Voz Mixta$$, 'Voz Mixta', $$Cantar una escala completa de una octava manteniendo la mezcla de registros de principio a fin, sin quiebres perceptibles.$$, $$Canta una escala mayor completa (una octava) del grave al agudo y de vuelta, manteniendo consistentemente la sensación de voz mixta — ni puramente de pecho, ni puramente de cabeza — en toda la extensión. Usa la vocal "E" cerrada o "I" para facilitar el equilibrio. Este ejercicio es exigente y debe interrumpirse ante la primera señal de fatiga vocal.$$, 15, 'Avanzado', array['voz-mixta','escala','avanzado','equilibrio'], 21),

-- Extensión Vocal
($$Escala Cromática Ascendente$$, 'Extensión Vocal', $$Ampliar la extensión vocal de forma gradual y segura, trabajando semitono a semitono.$$, $$Canta una escala cromática (subiendo semitono a semitono) partiendo de una nota cómoda, usando la vocal "A". Avanza solo hasta donde la voz permanezca cómoda y sin esfuerzo perceptible, marcando mentalmente el punto de parada de cada sesión para acompañar la evolución de la extensión a lo largo de las semanas.$$, 10, 'Intermedio', array['extensión','cromática','gradual','intermedio'], 22),

($$Alargamiento de Extensión con Glissando Amplio$$, 'Extensión Vocal', $$Alargar suavemente los límites de la extensión vocal sin forzar la voz.$$, $$Ejecuta glissandos amplios, del grave más cómodo al agudo más cómodo y viceversa, en la vocal "U", intentando ganar un poco más de amplitud en cada repetición — pero siempre respetando el límite de comodidad del día. La extensión vocal se expande con consistencia a lo largo del tiempo, no con fuerza en una sola sesión.$$, 10, 'Intermedio', array['extensión','glissando','alargamiento','intermedio'], 23),

($$Exploración de Notas Límite (Agudos y Graves)$$, 'Extensión Vocal', $$Mapear y expandir con seguridad los extremos actuales de la extensión vocal del alumno.$$, $$Con supervisión del profesor, explora cuidadosamente las notas más agudas y más graves que la voz consigue producir con calidad (sin forzar ni "quebrarse"), documentando los límites actuales. Repite periódicamente para acompañar la evolución. Interrumpe de inmediato ante cualquier incomodidad en la garganta.$$, 15, 'Avanzado', array['extensión','límites','avanzado','mapeo'], 24),

-- Resonancia
($$Zumbido Nasal (Humming)$$, 'Resonancia', $$Localizar y activar la resonancia nasal y facial de forma simple y accesible.$$, $$Produce un zumbido (humming) con la boca cerrada, sintiendo la vibración en los labios, la nariz y la región de los huesos de la cara. Explora diferentes alturas, siempre buscando maximizar esa sensación de vibración facial, que indica buena resonancia.$$, 5, 'Principiante', array['resonancia','humming','principiante','cara'], 25),

($$Resonancia en "Ng" con Vibración Facial$$, 'Resonancia', $$Profundizar la sensación de resonancia nasal usando el sonido "Ng" (como en inglés "sing") en frases melódicas.$$, $$Canta pequeñas melodías usando solo el sonido "Ng", manteniendo la vibración concentrada en la región nasal y en los huesos de la cara durante toda la frase melódica. Luego, transfiere esa misma sensación de vibración a una vocal abierta, como "A", cantando la misma melodía.$$, 10, 'Intermedio', array['resonancia','ng','vibración','intermedio'], 26),

($$Proyección de Voz con Foco en la Máscara$$, 'Resonancia', $$Aumentar la proyección vocal utilizando la resonancia de la "máscara" facial, sin depender de fuerza en la garganta.$$, $$Canta frases enteras dirigiendo mentalmente el sonido hacia la región de la "máscara" (nariz, mejillas y frente), buscando una sensación de proyección natural sin aumentar el esfuerzo en la garganta. Compara el volumen percibido antes y después de ajustar el foco de resonancia — la diferencia debe ser perceptible sin esfuerzo extra.$$, 10, 'Avanzado', array['resonancia','proyección','máscara','avanzado'], 27),

-- Dicción
($$Trabalenguas Vocalizados$$, 'Dicción', $$Mejorar la agilidad articulatoria de la lengua y los labios a través de trabalenguas cantados.$$, $$Elige un trabalenguas simple y corto y cántalo en una nota o escala corta, articulando cada consonante con claridad exagerada. Aumenta la velocidad gradualmente, sin sacrificar la claridad de la pronunciación.$$, 5, 'Principiante', array['dicción','trabalenguas','articulación','principiante'], 28),

($$Consonantes Explosivas en Staccato$$, 'Dicción', $$Fortalecer la precisión y la energía en la articulación de consonantes explosivas (P, T, K, B, D, G).$$, $$Canta secuencias cortas repitiendo consonantes explosivas aisladas (por ejemplo "Pa-Pa-Pa-Pa", "Ta-Ta-Ta-Ta", "Ka-Ka-Ka-Ka") en staccato rápido, en una sola nota. Siente el impulso de aire de cada consonante viniendo del apoyo abdominal, no solo de la boca.$$, 10, 'Intermedio', array['dicción','consonantes','staccato','intermedio'], 29),

($$Texto Cantado con Articulación Exagerada$$, 'Dicción', $$Aplicar la dicción trabajada en un contexto musical real, manteniendo claridad incluso en pasajes rápidos o agudos.$$, $$Elige un fragmento de una canción del repertorio del alumno y cántalo dos veces: primero exagerando a propósito cada consonante y vocal, luego normalmente — pero buscando mantener parte de esa claridad conquistada. Graba las dos versiones y compara la inteligibilidad del texto entre ellas.$$, 15, 'Avanzado', array['dicción','repertorio','articulación','avanzado'], 30)

on conflict (title) where teacher_id is null do nothing;
